# ===============================
# = Spring configurations
# ===============================
spring:
  name: local
  # = HTTP requests configurations ##############################
  servlet:
    multipart:
      location: /tmp
  datasource:
    url:      ${env.SPRING_DATASOURCE_URL}
    username: ${env.SPRING_DATASOURCE_USERNAME}
    password: ${env.SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
